
title: Indigo's Blog
email: contact@indigonolan.com
description: >-
  A blog by Indigo Nolan
baseurl: ""
url: "https://indigo.spot"

collections:
  tils:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - .templates
  - template.config.js
  - README.md
  - Gemfile.lock
  - vendor
  - push-changes
  - pull-changes
include:
  - daylio/vendor