// daylio.js - Handles file upload, cleaning, and download UI for Daylio Text Logs

const uploadInput = document.getElementById('csv-upload');
const downloadSection = document.getElementById('download-section');
const csvLinks = document.getElementById('csv-links');
const downloadZipBtn = document.getElementById('download-zip');

function downloadBlob(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }, 100);
}

async function createZip(files) {
    if (typeof JSZip === 'undefined') {
        alert('ZIP download requires JSZip.');
        return null;
    }
    const zip = new JSZip();
    // Loop through the dynamic file names generated by clean.js
    for (const [filename, content] of Object.entries(files)) {
        zip.file(filename, content);
    }
    return await zip.generateAsync({type: 'blob'});
}

uploadInput.addEventListener('change', async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    
    const text = await file.text();
    const cleaned = window.cleanDaylioCSV(text); // Returns { "YYYY-P1.txt": string, ... }
    
    csvLinks.innerHTML = '';
    downloadSection.style.display = 'block';
    
    let fileCount = 0;
    
    for (const filename of Object.keys(cleaned).sort()) {
        fileCount++;
        const btn = document.createElement('button');
        btn.className = 'download-btn';
        btn.textContent = `Download ${filename}`;
        // Note: Using text/plain now instead of text/csv
        btn.onclick = () => downloadBlob(new Blob([cleaned[filename]], {type:'text/plain'}), filename);
        csvLinks.appendChild(btn);
    }
    
    if (fileCount > 1) {
        downloadZipBtn.style.display = 'inline-block';
        downloadZipBtn.onclick = async () => {
            if (typeof JSZip === 'undefined') {
                const script = document.createElement('script');
                script.src = 'https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';
                script.onload = async () => {
                    const zipBlob = await createZip(cleaned);
                    if (zipBlob) downloadBlob(zipBlob, 'daylio_logs.zip');
                };
                document.body.appendChild(script);
            } else {
                const zipBlob = await createZip(cleaned);
                if (zipBlob) downloadBlob(zipBlob, 'daylio_logs.zip');
            }
        };
    } else {
        downloadZipBtn.style.display = 'none';
    }
});